import { readdir, writeFile, stat } from "node:fs/promises";
import { resolve, relative, dirname, join } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const drizzleDir = resolve(repoRoot, "drizzle");
const journalPath = resolve(drizzleDir, "meta/_journal.json");
const outPath = resolve(repoRoot, "src/bun/db/migrations.generated.ts");

async function walk(dir: string, out: string[] = []): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) await walk(full, out);
    else if (entry.isFile()) out.push(full);
  }
  return out;
}

await stat(journalPath); // fail fast if drizzle wasn't generated
const files = (await walk(drizzleDir)).sort();

function rel(target: string): string {
  const r = relative(dirname(outPath), target).replaceAll("\\", "/");
  return r.startsWith(".") ? r : "./" + r;
}

const lines: string[] = [
  "// Auto-generated by scripts/generate-migrations.ts — do not edit by hand.",
  "// Re-run `bun run db:generate` after adding migrations so the binary embeds them.",
  "",
  `// @ts-ignore — Bun import attribute: returns a string path, not parsed JSON.`,
  `import _journal from "${rel(journalPath)}" with { type: "file" };`,
];

files.forEach((file, i) => {
  if (file === journalPath) return;
  lines.push(
    `// @ts-ignore — Bun import attribute: returns a string path.`,
  );
  lines.push(`import _f${i} from "${rel(file)}" with { type: "file" };`);
});

lines.push("");
const otherIdx = files.map((_, i) => i).filter((i) => files[i] !== journalPath);
lines.push(`const embedded = [${otherIdx.map((i) => `_f${i}`).join(", ")}];`);
lines.push("void embedded;");
lines.push("");
lines.push(
  "// drizzle reads <migrationsFolder>/meta/_journal.json then the per-entry .sql files.",
);
lines.push(`const journalPath = _journal as unknown as string;`);
lines.push(
  `export const migrationsFolder = journalPath.replace(/[\\/\\\\]meta[\\/\\\\][^\\/\\\\]+$/, "");`,
);
lines.push("");

await writeFile(outPath, lines.join("\n"), "utf8");
console.log(
  `Embedded ${files.length} file(s) from drizzle/ — wrote ${relative(repoRoot, outPath)}`,
);
